export const FETCH_ALL_NCEA_REQUEST = 'FETCH_ALL_NCEA_REQUEST';
export const SET_NCEA = 'SET_NCEA';

//************//

export const FETCH_ALL_DEBT_INFO = 'FETCH_ALL_DEBT_INFO';
export const FETCH_ALL_DEBT_INFO_REQUEST = 'FETCH_ALL_DEBT_INFO_REQUEST';

export const FETCH_BY_ID_BANK_CHECK = 'FETCH_BY_ID_BANK_CHECK';
export const SET_BANK_CHECK = 'SET_BANK_CHECK';

export const FETCH_PERSONS_CHECKS = 'FETCH_PERSONS_CHECKS';
export const SET_PERSONS_CHECKS = 'SET_PERSONS_CHECKS';

export const FETCH_PERSONS_TAXES = "FETCH_PERSONS_TAXES";
export const FETCH_PERSONS_TAXES_REQUEST = "FETCH_PERSONS_TAXES_REQUEST";

//************//

export const CREATE_BANK_CHECK_REQUEST = 'CREATE_BANK_CHECK_REQUEST';
export const CREATE_BANK_CHECK = 'CREATE_BANK_CHECK';

export const UPDATE_BANK_CHECK_REQUEST = 'UPDATE_BANK_CHECK_REQUEST';
export const UPDATE_BANK_CHECK = 'UPDATE_BANK_CHECK';

//************//

export const POST_DECLARATION = 'POST_DECLARATION';
export const CREATE_DECLARATION = 'CREATE_DECLARATION';

export const UPDATE_DECLARATION = 'UPDATE_DECLARATION';
export const UPDATE_DECLARATION_REQUEST = 'UPDATE_DECLARATION_REQUEST';

//************//

export const CREATE_ENTITY = 'CREATE_ENTITY';
export const CREATE_SELF_PERSON = 'CREATE_SELF_PERSON';
export const CREATE_INDIVID = 'CREATE_INDIVID';



export const DELETE_DECLARATION = 'DELETE_DECLARATION';

export const GET_AUTH_TOKEN_REQUEST = 'GET_AUTH_TOKEN_REQUEST'
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN'
export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST'
export const SIGN_OUT = 'SIGN_OUT'

//************//

export const REGISTRATE = 'REGISTRATE'
export const SET_PERSON_ID = 'SET_PERSON_ID'
export const SET_EMPLOYEE_ID = 'SET_EMPLOYEE_ID'
export const SET_REG_INFO = 'SET_REG_INFO'