export const FETCH_ALL_DEBT_INFO = 'FETCH_ALL_DEBT_INFO';
export const FETCH_ALL_NCEA = 'FETCH_ALL_NCEA';
export const FETCH_BY_ID_BANK_CHECK = 'FETCH_BY_ID_BANK_CHECK';
export const FETCH_PERSONS_CHECKS = 'FETCH_PERSONS_CHECKS';
export const FETCH_PERSONS_DECLARATIONS = "FETCH_PERSONS_DECLARATIONS";

export const CREATE_BANK_CHECK = 'CREATE_BANK_CHECK';
export const CREATE_DECLARATION = 'CREATE_DECLARATION';
export const CREATE_ENTITY = 'CREATE_ENTITY';
export const CREATE_SELF_PERSON = 'CREATE_SELF_PERSON';
export const CREATE_INDIVID = 'CREATE_INDIVID';

export const UPDATE_BANK_CHECK = 'UPDATE_DECLARATION';
export const UPDATE_DECLARATION = 'UPDATE_DECLARATION';

export const DELETE_DECLARATION = 'DELETE_DECLARATION';

export const GET_AUTH_TOKEN = 'GET_AUTH_TOKEN'
export const SIGN_OUT = 'SIGN_OUT'
export const REGISTRATE = 'REGISTRATE'
export const SET_PERSON_ID = 'SET_PERSON_ID'
export const SET_EMPLOYEE_ID = 'SET_EMPLOYEE_ID'
export const SET_REG_INFO = 'SET_REG_INFO'