
export const ACTION_TYPES = {
    CREATE: 'CREATE',
    DELETE: 'DELETE',
    UPDATE: 'UPDATE',
    FETCH_ALL: 'FETCH_ALL'
}

export const FETCH_ALL_DEBT_INFO = 'FETCH_ALL_DEBT_INFO';
export const FETCH_ALL_ENTITIES = 'FETCH_ALL_ENTITIES';
export const FETCH_ALL_NCEA = 'FETCH_ALL_NCEA';
export const FETCH_BY_ID_BANK_CHECK = 'FETCH_BY_ID_BANK_CHECK';
export const CREATE_DECLARATION = 'CREATE_DECLARATION';
export const UPDATE_DECLARATION = 'UPDATE_DECLARATION';
export const DELETE_DECLARATION = 'DELETE_DECLARATION';