import React from "react";
import { Table, Container } from "react-bootstrap";

export const Users = () => (
  <Container>
    <Table stripted brdered hover>
      <thead>
        <tr>
          <th>#</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Username</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>1</th>
          <th>Den</th>
          <th>Brat</th>
          <th>@zxc</th>
        </tr>
        <tr>
          <th>2</th>
          <th>Igor</th>
          <th>Loh</th>
          <th>@Japan</th>
        </tr>
        <tr>
          <th>3</th>
          <th>Valera</th>
          <th>Volkov</th>
          <th>@Lone_Marshal</th>
        </tr>
        <tr>
          <th>1</th>
          <th>Den</th>
          <th>Brat</th>
          <th>@zxc</th>
        </tr>
        <tr>
          <th>2</th>
          <th>Igor</th>
          <th>Loh</th>
          <th>@Japan</th>
        </tr>
        <tr>
          <th>3</th>
          <th>Valera</th>
          <th>Volkov</th>
          <th>@Lone_Marshal</th>
        </tr>
        <tr>
          <th>1</th>
          <th>Den</th>
          <th>Brat</th>
          <th>@zxc</th>
        </tr>
        <tr>
          <th>2</th>
          <th>Igor</th>
          <th>Loh</th>
          <th>@Japan</th>
        </tr>
        <tr>
          <th>3</th>
          <th>Valera</th>
          <th>Volkov</th>
          <th>@Lone_Marshal</th>
        </tr>
        <tr>
          <th>1</th>
          <th>Den</th>
          <th>Brat</th>
          <th>@zxc</th>
        </tr>
        <tr>
          <th>2</th>
          <th>Igor</th>
          <th>Loh</th>
          <th>@Japan</th>
        </tr>
        <tr>
          <th>3</th>
          <th>Valera</th>
          <th>Volkov</th>
          <th>@Lone_Marshal</th>
        </tr>
      </tbody>
    </Table>
  </Container>
);
